### ISSUE TITLE
Suggestion: Show ongoing operation on screen.

### ISSUE THREAD

**Issue by exegg** [SimpleMobileTools/Simple-Calculator#56]
It's simple but I think is weird the app doesn't show whatever operation I'm doing. For example, I want to calculate 20 + 5, the app doesn't show when I hit the "+". It will only show 20, then register my operation silently, then the 5. This is odd, and I think it can be easy solved with just displaying the current operation on screen. Thanks.

**Comment by ModestosV** [comment]
A message to @tibbi . For a school project, my team and I forked your repo (Thank you!) and have been working on a lot of the features that users have requested for your calculator, while trying to keep the "Simple" feel, including handling full functions rather than number - operation - number. You can check it out here: https://github.com/ModestosV/Simple-Calculator-DreamTeam 

There are still many bugs (no widget, broken rotate) as it is a work in progress, but if you'd like, you can email me at modestosvergados@gmail.com and I can try and work on some of the issues on your app, without changing the core of your code (which is basically what my team and I have done).

**Comment by tibbi** [comment]
ye Ive seen the pull requests, but I dont want to accept something that rewrites the whole app.. I will update the app someday, but the calculator isnt really a priority for now.

**Comment by ModestosV** [comment]
I meant I would **not** do the same thing to your app. No additional libraries, no deleting methods.

Regardless, feel free to let me know in the future if it again becomes a priority for you.

**Comment by aunwin** [comment]
This becomes especially confusing when one enters a number then presses the C and entering a number times another number again. E.g. press 4 -> press clear - (display jumps to 0) - > press 5 * 6 --> The result is not 30 as expected but 0 since the calculater calculated 0 * 5 = 0 and 0 * 6 = 0.

**Comment by tibbi** [comment]
has been added already
